### ISSUE TITLE
Error when building app:Object literal may only specify known properties, and 'cert' does not exist in type 'PassportSamlConfig'

### ISSUE THREAD

**Issue by fvarga01** [joshuawwright/saml-sso-express-passport-docker-example#1]
Error observed when trying to run the express server: 

TS2769: No overload matches this call.
  Overload 1 of 2, '(options: PassportSamlConfig, signonVerify: VerifyWithRequest, logoutVerify: VerifyWithRequest): Strategy', gave the following error.
    Object literal may only specify known properties, and 'cert' does not exist in type 'PassportSamlConfig'.
  Overload 2 of 2, '(options: PassportSamlConfig, signonVerify: VerifyWithoutRequest, logoutVerify: VerifyWithoutRequest): Strategy', gave the following error.
    Object literal may only specify known properties, and 'cert' does not exist in type 'PassportSamlConfig'.

  13 |     decryptionPvk: readFileSync(`./certs/key.pem`, 'utf8'),
  14 |     privateKey: readFileSync(`./certs/key.pem`, 'utf8'),
> 15 |     cert: readFileSync(`./certs/idp.pem`, 'utf8')
     |     ^
  16 |   },
  17 |   ((profile, done) => done(null, profile)) as VerifyWithoutRequest,
  18 |   ((profile, done) => done(null, profile)) as VerifyWithoutRequest

Found 1 error.
[ watch ] build finished with errors (see above), watching for changes...
Build failed, waiting for changes to restart...

Fixed by changing this line:

 cert: readFileSync(`./certs/idp.pem`, 'utf8')

to

 idpCert: readFileSync(`./certs/idp.pem`, 'utf8')

Thanks for the tutorial btw!

**Comment by joshuawwright** [comment]
Hi @fvarga01. Thanks for bringing this to my attention.

 Unfortunately, I am not able to replicate this issue. Are are we using the same Strategy?

I am importing my strategy on line 6 of main.ts:
`import { Strategy, VerifyWithoutRequest } from '@node-saml/passport-saml';`

In the types I am unable to find any support for the key "idpCert".
```
export interface MandatorySamlOptions {
    cert: string | string[] | CertCallback;
    issuer: string;
}
```

```
export interface SamlOptions extends Partial<SamlSigningOptions>, MandatorySamlOptions {
    callbackUrl?: string;
    path: string;
    protocol?: string;
    host: string;
    entryPoint?: string;
    decryptionPvk?: string | Buffer;
    additionalParams: Record<string, string>;
    additionalAuthorizeParams: Record<string, string>;
    identifierFormat: string | null;
    allowCreate: boolean;
    spNameQualifier?: string | null;
    acceptedClockSkewMs: number;
    attributeConsumingServiceIndex?: string;
    disableRequestedAuthnContext: boolean;
    authnContext: string[];
    forceAuthn: boolean;
    skipRequestCompression: boolean;
    authnRequestBinding?: string;
    racComparison: RacComparision;
    providerName?: string;
    passive: boolean;
    idpIssuer?: string;
    audience: string | false;
    scoping?: SamlScopingConfig;
    wantAssertionsSigned: boolean;
    wantAuthnResponseSigned: boolean;
    maxAssertionAgeMs: number;
    generateUniqueId: () => string;
    signMetadata: boolean;
    validateInResponseTo: ValidateInResponseTo;
    requestIdExpirationPeriodMs: number;
    cacheProvider: CacheProvider;
    logoutUrl: string;
    additionalLogoutParams: Record<string, string>;
    logoutCallbackUrl?: string;
    disableRequestAcsUrl: boolean;
    samlAuthnRequestExtensions?: Record<string, unknown>;
    samlLogoutRequestExtensions?: Record<string, unknown>;
    metadataContactPerson?: {
        "@contactType": "technical" | "support" | "administrative" | "billing" | "other";
        Extensions?: string;
        Company?: string;
        GivenName?: string;
        SurName?: string;
        EmailAddress?: [string];
        TelephoneNumber?: [string];
    }[];
    metadataOrganization?: {
        OrganizationName: {
            "@xml:lang": string;
            "#text": string;
        }[];
        OrganizationDisplayName: {
            "@xml:lang": string;
            "#text": string;
        }[];
        OrganizationURL: {
            "@xml:lang": string;
            "#text": string;
        }[];
    };
}
```

Do we have different dependency versions?
